### ISSUE TITLE
Warning: QActivation could not be transformed and will be executed as-is

### ISSUE THREAD

**Issue by IlkayW** [google/qkeras#5] opened 2020-01-15 13:46 UTC
Hello,

first I have to thank you for this great repository. However, I always receive this strange warning as mentioned below. I am using the following version of packages with Spyder 4.1. Is this a warning which can be ignored and if so, how can I suppress this message?

## Packages
  tensorflow  version: 2.0.0
  keras       version: 2.2.4-tf
  numpy       version: 1.17.4
  opencv      version: 4.1.2 

## Warning
WARNING: Entity <bound method QActivation.call of <Utils.qkeras.qlayers.QActivation object at 0x000001C0816E5390>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause:

**Comment by zhuangh** [comment] 2020-01-15 17:04
@IlkayW which qkeras version you are using, do you have the git commit hash or SHA? thanks!

**Comment by IlkayW** [comment] 2020-01-15 19:27
Thank you for your quick response :)
I just cloned the repo today (15.01.2020) and transfered the qkeras stuff to my own project. 
I mean it's working, but there are tons of these warnings which is worrisome to me.

**Comment by zhuangh** [comment] 2020-01-19 20:59
@IlkayW thanks for that. I have not encountered this yet. If you use that commit, I suggest you try tensorflow 2.1.0. We start to use tf.keras instead of standalone Keras. And there are something missing in the tf.keras of tensorflow 2.0.0, which I have made fixes, e.g., the missing API [depthwise_conv](https://github.com/tensorflow/tensorflow/blob/67330f736ee45c8a282f6e3b558aa633a4ca1b48/tensorflow/python/keras/layers/convolutional.py#L1888).

BTW, I have not been able to reproduce your warnings. We will keep eyes on it. But if you know how to fix, PRs from you are welcome :)

**Comment by zhuangh** [comment] 2020-02-17 20:58
close this issue since it has been quiet for a while. feel free to reopen it if anything else comes up.

**Closed by zhuangh** 2020-02-17 20:58 UTC
